"""exchange_rate

Revision ID: 0d5b592680cf
Revises: cafb063bb7f9
Create Date: 2026-04-17 09:53:09.279398

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d5b592680cf"
down_revision: Union[str, None] = "cafb063bb7f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("base_currency_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["base_currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "date", "currency_id", "base_currency_id", name="uq_date_currency"
        ),
    )
    op.create_index(
        op.f("ix_exchange_rate_date"), "exchange_rate", ["date"], unique=False
    )
    op.create_index(op.f("ix_exchange_rate_id"), "exchange_rate", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rate_id"), table_name="exchange_rate")
    op.drop_index(op.f("ix_exchange_rate_date"), table_name="exchange_rate")
    op.drop_table("exchange_rate")
    # ### end Alembic commands ###
