"""add all table

Revision ID: 237d701704b6
Revises: 9cf8c4427ea1
Create Date: 2026-04-14 09:37:11.702314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "237d701704b6"
down_revision: Union[str, None] = "9cf8c4427ea1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brand_id"), "brand", ["id"], unique=False)
    op.create_table(
        "category",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_category_id"), "category", ["id"], unique=False)
    op.create_table(
        "matrix_type",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_matrix_type_id"), "matrix_type", ["id"], unique=False)
    op.create_table(
        "os",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_os_id"), "os", ["id"], unique=False)
    op.create_table(
        "screen_resolution",
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_screen_resolution_id"), "screen_resolution", ["id"], unique=False
    )
    op.create_table(
        "shop",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_shop_id"), "shop", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.CHAR(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "tv",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("os_id", sa.Integer(), nullable=True),
        sa.Column("screen_resolution_id", sa.Integer(), nullable=True),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("matrix_type_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("refresh_rate", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matrix_type_id"],
            ["matrix_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["os_id"],
            ["os.id"],
        ),
        sa.ForeignKeyConstraint(
            ["screen_resolution_id"],
            ["screen_resolution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tv_id"), "tv", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tv_id"), table_name="tv")
    op.drop_table("tv")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_shop_id"), table_name="shop")
    op.drop_table("shop")
    op.drop_index(op.f("ix_screen_resolution_id"), table_name="screen_resolution")
    op.drop_table("screen_resolution")
    op.drop_index(op.f("ix_os_id"), table_name="os")
    op.drop_table("os")
    op.drop_index(op.f("ix_matrix_type_id"), table_name="matrix_type")
    op.drop_table("matrix_type")
    op.drop_index(op.f("ix_category_id"), table_name="category")
    op.drop_table("category")
    op.drop_index(op.f("ix_brand_id"), table_name="brand")
    op.drop_table("brand")
    # ### end Alembic commands ###
