"""token

Revision ID: 4f3c830eb262
Revises: 408e357d243f
Create Date: 2026-04-29 15:24:16.099091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f3c830eb262"
down_revision: Union[str, None] = "408e357d243f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.CHAR(length=128),
        type_=sa.String(length=60),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=60),
        type_=sa.CHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
