"""shoplink

Revision ID: 69af60b8617a
Revises: 237d701704b6
Create Date: 2026-04-15 12:05:33.966563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69af60b8617a"
down_revision: Union[str, None] = "237d701704b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_link",
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("tv_id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=250), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shop.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tv_id"],
            ["tv.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_link_id"), "shop_link", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shop_link_id"), table_name="shop_link")
    op.drop_table("shop_link")
    # ### end Alembic commands ###
