"""add diagonal

Revision ID: d3f5c04cdcd8
Revises: be1e0cb15344
Create Date: 2026-05-15 15:21:17.999484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3f5c04cdcd8"
down_revision: Union[str, None] = "be1e0cb15344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tv", sa.Column("diagonal", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tv", "diagonal")
    # ### end Alembic commands ###
