"""change fild

Revision ID: eb0f099ba8d9
Revises: 4f3c830eb262
Create Date: 2026-05-14 20:35:44.547308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb0f099ba8d9"
down_revision: Union[str, None] = "4f3c830eb262"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("day_price", sa.Column("date", sa.Date(), nullable=False))
    op.drop_column("day_price", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_price",
        sa.Column("created_at", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("day_price", "date")
    # ### end Alembic commands ###
