"""DayPrice2

Revision ID: f91dbb083f8e
Revises: 812bc971ae36
Create Date: 2026-04-15 13:40:42.992049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f91dbb083f8e"
down_revision: Union[str, None] = "812bc971ae36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("name", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)
    op.create_table(
        "day_price",
        sa.Column("shop_link_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("discount_price", sa.Float(), nullable=True),
        sa.Column("card_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_link_id"],
            ["shop_link.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_day_price_id"), "day_price", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_day_price_id"), table_name="day_price")
    op.drop_table("day_price")
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
